language: ruby
services:
- docker
cache:
- bundler
install:
- bundle install
rvm:
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-disk-checks.gemspec
- gem install sensu-plugins-disk-checks-*.gem
before_deploy:
- git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
deploy:
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-disk-checks
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
env:
  global:
    secure: "TMfJ78XvU2xqH5fD95UYQxWASz1M+SrGuAk7LoJrV5nCmrUjZh2Hgar0tdHSxyR80DAvaudpHggoZole1u7uokhr1LDCxjeBO44wgo6/j1qCsjeLJy65SFzyC6c6JYFNCUmEyMqineLiYEB2kNZvpTSre8+VU1sqCHzkfKpEdZIgPMufFOdPgQUezE3TyYxyZ8u2MgNAVROweuFHnkmctALLN3oNfSrEIhktF+t+TFuFlT+itsPS+vLPdZ/FU2yEDyqvgh25DLKbp5H5kBxl0ZBVD9NYZhBqxxqehLCqALWVMozZspN3tlcY2wKMcK6352pikBgZOj+eOa8x1S+Im7XYwBXC5g6KUgW2XAw5ym/BgEd6nRkg1cAYgZy2pZtYe3yuzdRd/Yvy80CHTOocRqRp5Zi7q27OA7lwKJrvxuBuy9yTDvQFvhjsQDX/24U3Zu2LFhuyjQYiQssS1erBfGere85h5bskIF5Hmbg9yCeiLPHCa2VIquhEQ8GwkGn99n4wwQckN6YBsenDa89MMHczD4JNTZBEeq03BPEH0a98RjAuIy+VU5+6HMu8WyOWMY+L2n2O2sCqGkA7d8EH2cAzDDWBH492X26pQQWmWRClaiAuvTsXqL2R5oBWN9dJ8x5+k4fOo6GdGz01smVJ/SedXFCsa1wKZ3LFb+EASx8="
